<main ng-controller="animalController">
    <!-- Modal Trigger -->
    <a class="right waves-effect waves-light btn" ng-click="modal()"><i class="mdi mdi-plus"></i>Novo</a>
    <a class="right waves-effect waves-light btn purple" href="/animal/exportar" target="_blank"><i class="mdi mdi-download"></i>Exportar</a>

    <!-- MODAL NEW ANIMAL -->
    <div id="newAnimal" class="modal">
        <div  ng-show="aba == 1">
            <div class="modal-content">
                <h1 class="title-modal centered">{{titleModal}}</h1>
                <a href="#" style="color: black" class="icon-close-modal right" ng-click="closeModal()"><i class="mdi mdi-close"></i></a><br/><br/>
                <div class="row aba-animal">
                    <div class="col s12">
                        <a href="#" class="aba teal activeAba" ng-click="alterAba(1)">Dados</a>
                        <a href="#" class="aba brown" ng-click="alterAba(2)">Ração</a>
                        <a href="#" class="aba blue" ng-click="alterAba(3)">Vacina</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <form method="POST" action="#" name="formAnimal">
                            <div class="row" ng-show="!edit.id">
                                <div class="col s6">
                                    <p>
                                        <input ng-model="chekboxInsert" type="checkbox" id="chekboxInsert" />
                                        <label for="chekboxInsert">Cadastrar Vários?</label>
                                    </p>
                                </div>
                            </div>
                            <div ng-show="!chekboxInsert">
                                <div class="col s12 m6">
                                    <label class="active" for="dataNascimento">Data de Nascimento</label>
                                    <input class="validate" type="date" ng-model="edit.dataNascimento" ng-model-options="{timezone: 'UTC'}" name="dataNascimento" id="dataNascimento" data-label="Data de Nascimento" placeholder="Digite a data de nascimento" ng-required="true" ng-class="{'invalid-form': formAnimal.dataNascimento.$error.required}"/>
                                </div>
                                <div class="col s12 m6">
                                    <label class="active" for="custo">Custo</label>
                                    <input class="validate" type="number" ng-model="edit.custo" name="custo" id="custo" data-label="Custo" placeholder="Digite a preço pago pelo animal" ng-required="true" ng-class="{'invalid-form': formAnimal.custo.$error.required}"/>
                                </div>
                                <div class="col s12 m6">
                                    <label class="active" for="origem">Origem</label>
                                    <input class="validate" type="text" ng-model="edit.origem" name="origem" id="origem" data-label="Origem" placeholder="Digite a origem do animal" ng-required="true" ng-class="{'invalid-form': formAnimal.origem.$error.required}"/>
                                </div>
                                <div class="col s12">
                                    <label class="active" for="observacao">Observação</label>
                                    <textarea id="observacao" class="validate" type="textarea" ng-model="edit.observacao" name="observacao" placeholder="Digite a observação"></textarea>
                                </div>
                            </div>
                            <div ng-if="chekboxInsert">
                                <div class="col s12 m6">
                                    <label class="active" for="statusVenda">Quantidade</label>
                                    <input class="validate" type="number" ng-model="edit.quantidade" name="quantidade" id="quantidade" data-label="Quantidade" placeholder="Digite a quantidade de animais" ng-required="true" ng-class="{'invalid-form': formAnimal.quantidade.$error.required}"/>
                                </div>
                                <div class="col s12 m6">
                                    <label class="active" for="custoTotal">Custo Total</label>
                                    <input class="validate" type="number" ng-model="edit.custoTotal" name="custoTotal" id="custoTotal" data-label="custoTotal" placeholder="Será divido pela quantidade" ng-required="true" ng-class="{'invalid-form': formAnimal.custoTotal.$error.required}"/>
                                </div>
                                <div class="col s12 m6">
                                    <label class="active" for="origem">Origem</label>
                                    <input class="validate" type="text" ng-model="edit.origem" name="origem" id="origem" data-label="origem" placeholder="Digite a origem dos animais" ng-required="true" ng-class="{'invalid-form': formAnimal.origem.$error.required}"/>
                                </div>
                                <div class="col s12 m6">
                                    <label class="active" for="dataNascimento">Data de Nascimento</label>
                                    <input class="validate" type="date" name="dataNascimento" ng-model="edit.dataNascimento" ng-model-options="{timezone: 'UTC'}"/>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a class="btn modal-action waves-effect waves-green" ng-show="!chekboxInsert" ng-click="addAnimal()"><i class="mdi mdi-{{btnIcon}}"></i>{{btnSalvar}}</a>
                <a class="btn modal-action modal-close waves-effect waves-green" ng-show="chekboxInsert" ng-click="insertMultiple()">Inserir Vários</a>
            </div>
        </div>

        <!-- ABA RAÇÃO-->
        <div ng-show="aba == 2">
            <div class="modal-content">
                <h1 class="title-modal centered">Vincular Ração - Alimento</h1>
                <a href="#" style="color: black" class="icon-close-modal right" ng-click="closeModal()"><i class="mdi mdi-close"></i></a><br/><br/>
                <div class="row aba-animal">
                    <div class="col s12">
                        <a href="#" class="aba teal" ng-click="alterAba(1)">Dados</a>
                        <a href="#" class="aba brown activeAba" ng-click="alterAba(2)">Ração</a>
                        <a href="#" class="aba blue" ng-click="alterAba(3)">Vacina</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <form method="POST" action="#" name="formRacao">
                            <div class="col s12 m6">
                                <label class="active" for="racao">Ração</label>
                                <select class="browser-default" name="idRacao" id="idRacao" data-label="Ração" ng-model="model.idRacao" ng-options="racao.id as racao.nome for racao in racoes" ng-init="resetSelect()" ng-required="true" ng-class="{'invalid-form': formRacao.idRacao.$error.required}"></select>
                            </div>
                            <div class="col s12 m6">
                                <label class="active" for="quantidade">Quantidade</label>
                                <input class="validate" type="number" name="quantidade" id="quantidade" data-label="Quantidade" ng-model="model.quantidade" placeholder="Digite a quantidade" ng-required="true" ng-class="{'invalid-form': formRacao.quantidade.$error.required}"/>
                            </div>
                            <div class="col s12 m6">
                                <label class="active" for="dataInicial">Data Inicial</label>
                                <input class="validate" type="date" name="dataInicial" id="dataInicial" data-label="Data Inicial" ng-model="model.dataInicial" ng-required="true" ng-class="{'invalid-form': formRacao.dataInicial.$error.required}"/>
                            </div>
                            <div class="col s12 m6" style="padding-top: 20px;">
                                <a class="btn modal-action waves-effect waves-green brown lighten-1" ng-click="addRacao()" style="width: 100%;">Adicionar</a>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12" ng-show="listRacoes != ''">
                        <table class="striped centered responsive-table">
                            <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Ração</th>
                                    <th>Quantidade</th>
                                    <th>Data Inicial</th>
                                    <th>Data Final</th>
                                    <th>Ação</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="listRacao in listRacoes| orderBy: '-idRacaoItem'" ng-class="{'red lighten-5': listRacao.statusRacaoItem == 1}">
                                    <td>{{listRacao.idRacaoItem}}</td>
                                    <td>{{listRacao.racao}}</td>
                                    <td>{{listRacao.quantidade}} {{listRacao.unidadeMedida}}</td>
                                    <td>{{listRacao.dataInicial| tccDate}}</td>
                                    <td>{{listRacao.dataFinal| tccDate}}</td>
                                    <td>
                                        <!--{{listRacao.statusRacaoItem}}-->
                                        <a style="cursor: pointer" ng-click="interromperRacao(listRacao.idRacaoItem)" ng-show="listRacao.statusRacaoItem == 0">Interromper</a>
                                        <!--<a style="cursor: pointer" ng-click="excluir(listRacao.id)">Excluir</a>-->
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>

        <!-- ABA VACINA-->
        <div ng-show="aba == 3">
            <div class="modal-content">
                <h1 class="title-modal centered">Vacinas - Medicamentos aplicados</h1>
                <a href="#" style="color: black" class="icon-close-modal right" ng-click="closeModal()"><i class="mdi mdi-close"></i></a><br/><br/>
                <div class="row aba-animal">
                    <div class="col s12">
                        <a href="#" class="aba teal" ng-click="alterAba(1)">Dados</a>
                        <a href="#" class="aba brown" ng-click="alterAba(2)">Ração</a>
                        <a href="#" class="aba blue activeAba" ng-click="alterAba(3)">Vacina</a>
                        <p ng-show="details == ''">Não há nenhuma aplicação com este animal ainda!</p>
                    </div>
                </div>
                <div class="row" ng-show="details != ''">
                    <div class="col s12">
                        <table class="striped centered responsive-table">
                            <thead>
                                <tr>
                                    <th>Código da Aplicação</th>
                                    <th>Vacina</th>
                                    <th>Descrição</th>
                                    <th>Data de Aplicação</th>
    <!--                                <th>Ações</th>-->
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="detail in details| orderBy: '-id'">
                                    <td>{{detail.idVacinaAplicacao}}</td>
                                    <td>{{detail.nomeVacina}}</td>
                                    <td>{{detail.descricao| truncate : 35}}</td>
                                    <td>{{detail.dataAplicacao| tccDate}}</td>
    <!--                                <td>
                                        <a style="cursor: pointer" ng-click="modal(animal)">Editar</a> | 
                                        <a style="cursor: pointer" ng-click="excluir(animal.id)">Excluir</a>
                                    </td>-->
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- MODAL VENDER ANIMAL -->
    <div id="sell-modal" class="modal">
        <div class="modal-content">
            <h1 class="title-modal centered">Inserir Pedido</h1>
            <a href="#" ng-click="closeModal()" style="color: black" class="icon-close-modal right"><i class="mdi mdi-close"></i></a>
            <div class="row">
                <div class="col s12">
                    <form name="formPedido" method="POST" action="#">
                        <div class="col s6">
                            <label class="active" for="numeroDocumento">Nº do Documento</label>
                            <input class="validate" id="numeroDocumento" type="text" name="numeroDocumento" ng-model="model.numeroDocumento" required/>
                        </div>
                        <div class="col s6">
                            <label class="active" for="dataCriacao">Data de Criação</label>
                            <input class="validate" type="date" name="dataCriacao" ng-model="model.dataCriacao" required/>
                        </div>
                        <div class="col s6">
                            <label class="active" for="valorTotal">Valor Total</label>
                            <input class="validate" type="number" name="valorTotal" ng-model="model.valorTotal" required/>
                        </div>
                        <div class="col s6">
                            <label class="active" for="cliente">Clientes</label>
                            <select class="browser-default" ng-model="model.idCliente" ng-options="cliente.id as cliente.nome for cliente in clientes" ng-init="resetSelect()"></select>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <a class="btn modal-action modal-close waves-effect waves-green" ng-click="addPedido()"><i class="mdi mdi-check"></i>Salvar</a>
        </div>
    </div>

    <!-- LISTAGEM DOS ANIMAIS -->
    <div class="row">
        <div class="col s12 m6 visualizacao-animal">
            <label>Status do Animal</label>
            <a class="cyan waves-effect" ng-click="filterListAnimal.statusVenda = null" ng-class="{'active': filterListAnimal.statusVenda == null}">Todos</a>
            <a class="green waves-effect" ng-click="filterListAnimal.statusVenda = 0" ng-class="{'active': filterListAnimal.statusVenda == 0}">Abertos</a>
            <a class="red waves-effect" ng-click="filterListAnimal.statusVenda = 1" ng-class="{'active': filterListAnimal.statusVenda == 1}">Vendidos</a>
        </div>
    </div>
    <table class="striped centered responsive-table">
        <thead>
            <tr>
                <th>Código</th>
                <th>Data de Cadastro</th>
                <th>Custo</th>
                <th>Status da Venda</th>
                <th>Origem</th>
                <th ng-show="filterListAnimal.statusVenda != 1"><a class="waves-effect waves-light btn" ng-click="openSellModal()">Vender?</a></th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="animal in animais| filter: filterListAnimal | orderBy: '-id'">
                <td>{{animal.id}}</td>
                <td>{{animal.dataCadastro| tccDate}}</td>
                <td>{{animal.custo| currency : 'R$ '}}</td>
                <td>{{getStatusVenda(animal.statusVenda)}}</td>
                <td>{{animal.origem}}</td>
                <td ng-show="filterListAnimal.statusVenda != 1" style="z-index: 222">
                    <input ng-if="animal.statusVenda == 0" ng-model="list[animal.id]" ng-true-value="1" ng-false-value="0" type="checkbox" id="{{animal.id}}" />
                    <label for="{{animal.id}}"></label>
                </td>
                <td>
                    <!--<a style="cursor: pointer" ng-click="openDetailsModal(animal.id)">Ver</a> |-->
                    <a style="cursor: pointer" ng-click="modal(animal)">Ver/Editar</a> |
                    <a style="cursor: pointer" ng-click="deletar(animal.id)">Excluir</a>
                </td>
            </tr>
        </tbody>
    </table>
</main>
<!-- Usa-se a variável $animal pq no model uso o método extract() que transforma todos os indices de um array em uma variável -->