<main ng-controller="clienteController">
    <!-- Modal Trigger -->
    <a class="right waves-effect waves-light btn" ng-click="modal()">
        <i class="mdi mdi-plus"></i>Novo
    </a>

    <!-- MODAL NOVO CLIENTE -->
    <div id="newClient" class="modal">
        <div class="modal-content">
            <h1 class="title-modal centered">{{titleModal}}</h1>
            <a href="#" ng-click="closeModal()" style="color: black" class="right icon-close-modal"><i class="mdi mdi-close"></i></a>
            <div class="row">
                <div class="col s12">
                    <form method="POST" action="#">
                        <div class="col s12 m6">
                            <label class="active" for="nome">Nome</label>
                            <input class="validate" id="nome" type="text" name="nome" ng-model="model.nome" required/>
                        </div>
                        <div class="col s12 m6">
                            <label class="active" for="cpf">Cpf</label>
                            <input class="validate" id="cpf" type="text" name="cpf" ng-model="model.cpf" required/>
                        </div>
                        <div class="row">
                            <div class="col s12 m6">
                                <label class="active" for="estado">Estados</label>
                                <select class="browser-default" ng-model="model.idEstado" ng-change="getCidadeByEstado(model.idEstado)" ng-options="estado.id as estado.nome for estado in estados" ng-init="resetSelect()">
                                    <option value="">Selecione um estado</option>
                                </select>
                            </div>
                            <div class="col s12 m6">
                                <label class="active" for="cidade">Cidades</label>
                                <select class="browser-default" ng-model="model.idCidade" ng-options="cidade.id as cidade.nome for cidade in cidades" ng-init="resetSelect()">
                                    <option value="">Selecione uma cidade</option>
                                </select>
                            </div>
                        </div>
                        <div class="col s12 m6">
                            <label class="active" for="endereco">Endereço</label>
                            <input class="validate" id="endereco" type="text" name="endereco" ng-model="model.endereco" required/>
                        </div>
                        <div class="col s12 m2">
                            <label class="active" for="numeroCasa">N° da Casa</label>
                            <input class="validate" id="numeroCasa" type="text" name="numeroCasa" ng-model="model.numeroCasa" required/>
                        </div>
                        <div class="col s12 m4">
                            <label class="active" for="bairro">Bairro</label>
                            <input class="validate" id="bairro" type="text" name="bairro" ng-model="model.bairro" required/>
                        </div>
                        <div class="col s12 m6">
                            <label class="active" for="telefone">Telefone</label>
                            <input class="validate" id="telefone" type="text" name="telefone" ng-model="model.telefone" required/>
                        </div>
                        <div class="col s12 m6">
                            <label class="active" for="celular">Celular</label>
                            <input class="validate" id="celular" type="text" name="celular" ng-model="model.celular" required/>
                        </div>

                        <div class="col s12">
                            <label class="active" for="observacao">Observação</label>
                            <textarea id="observacao" class="validate" type="textarea" name="observacao" ng-model="model.observacao"></textarea>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <a class="btn modal-action modal-close waves-effect waves-green" ng-click="addClient()"><i class="mdi mdi-{{btnIcon}}"></i>{{btnSalvar}}</a>
        </div>
    </div>

    <table class="striped centered responsive-table">
        <thead>
            <tr>
                <th>Código</th>
                <th>Nome</th>
                <th>Telefone</th>
                <th>Data de Cadastro</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="cliente in clientes">
                <td>{{cliente.id}}</td>
                <td>{{cliente.nome}}</td>                
                <td>{{cliente.telefone}}</td>                
                <td>{{cliente.dataCadastro| tccDate}}</td>
                <td><a href="#" ng-click="modal(cliente)">Editar</a> | <a style="cursor: pointer" ng-click="deletar(cliente.id)">Excluir</a></td>
            </tr>
        </tbody>
    </table>
</main>