<main ng-controller="clienteController">
    <!-- Modal Trigger -->
    <a class="right waves-effect waves-light btn" ng-click="modal()"><i class="material-icons">add</i>Novo</a>
    <!--Modal Structure--> 
    <div id="newAnimal" class="modal">
        <div class="modal-content">
            <h4 style="display: inline">Cadastrar Animal</h4>
            <a href="#" style="color: black" class="closeModal right"><i class="material-icons">close</i></a>
            <div class="row">
                <div class="col s12">
                    <form method="POST" action="#">
                        <div class="input-field col s6">
                            <input class="validate" id="apelido" type="text" name="apelido" ng-model="edit.apelido" required/>
                            <label class="active" for="apelido">Apelido</label>
                        </div>
                        <div class="input-field col s6">
                            <input class="validate" type="date" name="dataNascimento" ng-model="edit.dataNascimento" required/>
                            <label class="active" for="dataNascimento">Data de Nascimento</label>
                        </div>
                        <div class="input-field col s6">
                            <input class="validate" type="number" name="custo" ng-model="edit.custo" required/>
                            <label class="active" for="custo">Custo</label>
                        </div>
                        <div class="input-field col s6">
                            <input class="validate" type="text" name="statusVenda" ng-model="edit.statusVenda" required/>
                            <label class="active" for="statusVenda">Status de Venda</label>
                        </div>
                        <div class="input-field col s12">
                            <input class="validate" type="text" name="observacao" ng-model="edit.observacao" required/>
                            <label class="active" for="observacao">Observação</label>
                        </div>
                        <div class="modal-footer">
                            <a class="btn modal-action modal-close waves-effect waves-green" ng-click="addAnimal()"><i class="material-icons">save</i> Salvar Animal</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <table class="striped centered responsive-table">
        <thead>
            <tr>
                <th>Código</th>
                <th>Nome</th>
                <th>Data de Cadastro</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="cliente in clientes">
                <td>{{cliente.id}}</td>
                <td>{{cliente.nome}}</td>                
                <td>{{cliente.teste}}</td>
                <td><a href="#" ng-click="modal(animal)">Editar</a> | <a style="cursor: pointer" ng-click="excluir(animal.id)">Excluir</a></td>
            </tr>
        </tbody>
    </table>
</main>