<main class="contato">

    <p>Em caso de dúvidas, sugestões ou problemas utilize um dos meios de comunicação abaixo:</p>

    <div class="row">
        <div class="col s12 m4">
            <i class="mdi mdi-cellphone-android"></i>
            <!--<label>Celular:</label>-->
            (43) 99918 - 1939
        </div>
        <div class="col s12 m4">
            <i class="mdi mdi-email-outline"></i>
            <!--<label>E-mail:</label>-->
            <a href="mailto:jean.carlos.otoni@gmail.com">jean.carlos.otoni@gmail.com</a>
        </div>
        <div class="col s12 m4">
            <div><i class="mdi mdi-linkedin"></i>
                <a target="_blank" href="https://www.linkedin.com/in/jean-otoni-a64507b3?trk=nav_responsive_tab_profile_pic">Linkedin</a>
            </div>
        </div> 
    </div>
</main>