<main ng-controller="pedidoController">
    <!-- Modal Trigger -->
    <a class="right waves-effect waves-light btn" ng-click="openModal()"><i class="mdi mdi-plus"></i>Novo</a>

    <!-- MODAL NOVO PEDIDO -->
    <div id="newPedido" class="modal">
        <form name="formPedido" method="POST" action="#">
            <div class="modal-content">
                <h1 class="title-modal">
                    <div>{{titleModal}}</div>
                    <a href="#" ng-click="closeModal()" style="color: black" class="icon-close-modal right"><i class="mdi mdi-close"></i></a>
                </h1>
                <div class="row">
                    <div class="col s12">
                        <div class="col s12 m6">
                            <label class="active" for="codigo">Nº do Documento</label>
                            <input class="validate" id="apelido" type="text" name="codigo" ng-model="model.numeroDocumento" required/>
                        </div>
                        <!--                        <div class="col s6">
                                                    <label class="active" for="dataCriacao">Data de Criação</label>
                                                    <input class="validate" type="date" name="dataCriacao" ng-model="model.dataCriacao" required/>
                                                </div>-->
                        <div class="col s12 m6">
                            <label class="active" for="valorTotal">Valor Total</label>
                            <input class="validate" type="number" name="valorTotal" ng-model="model.valorTotal" required/>
                        </div>
                        <div class="col s12 m6">
                            <label class="active" for="situacao">Clientes</label>
                            <select class="browser-default" ng-model="model.idCliente" ng-options="cliente.id as cliente.nome for cliente in clientes" ng-init="resetSelect()"></select>
                        </div>
                        <div class="col s12">
                            <label class="active" for="animais">Animais</label>
                            <p>Selecione os animais que deseja adicionar ao pedido.</p>
                            <div ng-repeat="animal in animais track by $index">
                                <div class="col s6 m3">
                                    <input ng-model="list[animal.id]" ng-true-value="1" ng-false-value="0" type="checkbox" id="{{animal.id}}" />
                                    <label for="{{animal.id}}">{{animal.id}}</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a class="btn modal-action modal-close waves-effect waves-green" ng-click="addPedido(1)"><i class="mdi mdi-pencil"></i>{{btnSalvar}}</a>
                <a class="btn modal-action modal-close waves-effect waves-green blue" ng-show="model.situacao == 1" ng-click="updateStatusPedido(2)"><i class="mdi mdi-cash-multiple"></i> Finalizar</a>
                <a class="btn modal-action modal-close waves-effect waves-green red" ng-show="model.situacao == 1" ng-click="updateStatusPedido(3)"><i class="mdi mdi-close"></i> Cancelar</a>
                <a class="btn modal-action modal-close waves-effect waves-green red" ng-show="model.situacao == 2" ng-click="updateStatusPedido(4)"><i class="mdi mdi-block-helper"></i> Estornar</a>
            </div>
        </form>
    </div>
    
    <table class="striped centered responsive-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Número Documento</th>
                <th>Cliente</th>
                <th>Data de Criação</th>
                <th>Valor Total</th>
                <th>Situação</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="pedido in pedidos">
                <td>{{pedido.id}}</td>
                <td>{{pedido.numeroDocumento}}</td>
                <td>{{pedido.nomeCliente}}</td>
                <td>{{pedido.dataCriacao| tccDate : "dd/MM/yyyy"}}</td>
                <td>{{pedido.valorTotal| currency: "R$ " }}</td>
                <td>{{getSituation(pedido.situacao)}}</td>
                <td><a href="#" ng-click="openModal(pedido)">Ver/Editar</a></td>
                <!--<a style="cursor: pointer" ng-click="excluir(pedido.id)">Excluir</a>-->
            </tr>
        </tbody>
    </table>
</main>


<!-- 
    -Criei as estruturas da classe pedidos dia 30/08, comecei a fazer um join com a tabela de clientes, porém estou com
    problemas na hora de alterar no banco ele meio que não permite alterar o cliente(não sei se é normal ser assim)
    -Quando continuar pegar para verificar o relacionamento com a tabela de animais, e fazer salvar, editar, excluir, etc
    -(renomear os métodos, e as requisições do service)
-->