<main ng-controller="pedidoController">
    <!-- Modal Trigger -->
    <a class="right waves-effect waves-light btn" ng-click="openModal()"><i class="mdi mdi-plus"></i>Novo</a>
    <!-- Modal Structure -->
    <div id="newPedido" class="modal">
        <div class="modal-content">
            <h1 class="title-modal">Inserir Pedido
                <a href="#" style="color: black" class="closeModal right"><i class="mdi mdi-close"></i></a>
            </h1>
            <div class="row">
                <div class="col s12">
                    <form name="formPedido" method="POST" action="#">
                        <div class="col s6">
                            <label class="active" for="codigo">Nº do Documento</label>
                            <input class="validate" id="apelido" type="text" name="codigo" ng-model="model.numeroDocumento" required/>
                        </div>
                        <div class="col s6">
                            <label class="active" for="dataCriacao">Data de Criação</label>
                            <input class="validate" type="date" name="dataCriacao" ng-model="model.dataCriacao" required/>
                        </div>
                        <div class="col s6">
                            <label class="active" for="valorTotal">Valor Total</label>
                            <input class="validate" type="number" name="valorTotal" ng-model="model.valorTotal" required/>
                        </div>
                        <div class="col s6">
                            <label class="active" for="situacao">Clientes</label>
                            <select class="browser-default" ng-model="model.idCliente" ng-options="cliente.id as cliente.nome for cliente in clientes" ng-init="resetSelect()"></select>
                        </div>
                        <div class="col s12">
                            <label class="active" for="situacao">Animais</label>
                            <!--{{animais}}-->
                            <div ng-repeat="animal in animais">
                                <input ng-model="sell[animal.id]" ng-true-value="1" ng-false-value="0" type="checkbox" id="{{animal.id}}" />
                                <label for="{{animal.id}}">{{animal.id}}</label>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <a class="btn modal-action modal-close waves-effect waves-green" ng-click="addPedido()"><i class="mdi mdi-check"></i> Adicionar Pedido</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <table class="striped centered responsive-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Número Documento</th>
                <th>Cliente</th>
                <th>Data de Criação</th>
                <th>Valor Total</th>
                <th>Situação</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="pedido in pedidos">
                <td>{{pedido.id}}</td>
                <td>{{pedido.numeroDocumento}}</td>
                <td>{{pedido.nomeCliente}}</td>
                <td>{{pedido.dataCriacao| date : "dd/MM/yyyy"}}</td>
                <td>{{pedido.valorTotal| currency: "R$ " }}</td>
                <td>{{pedido.situacao}}</td>
                <td><a href="#" ng-click="openModal(pedido)">Editar</a> | <a style="cursor: pointer" ng-click="excluir(pedido.id)">Excluir</a></td>
            </tr>
        </tbody>
    </table>
</main>


<!-- 
    -Criei as estruturas da classe pedidos dia 30/08, comecei a fazer um join com a tabela de clientes, porém estou com
    problemas na hora de alterar no banco ele meio que não permite alterar o cliente(não sei se é normal ser assim)
    -Quando continuar pegar para verificar o relacionamento com a tabela de animais, e fazer salvar, editar, excluir, etc
    -(renomear os métodos, e as requisições do service)
-->