<main ng-controller="pedidoController">
    <!-- Modal Trigger -->
    <a class="right waves-effect waves-light btn" ng-click="openModal()"><i class="mdi mdi-plus"></i>Novo</a>

    <a class="right waves-effect waves-light btn purple" href="/pedido/exportar" target="_blank"><i class="mdi mdi-download"></i>Exportar</a>

    <!-- MODAL NOVO PEDIDO -->
    <div id="newPedido" class="modal">
        <form name="formPedido" method="POST" action="#">
            <div class="modal-content">
                <h1 class="title-modal">
                    <div>{{titleModal}}</div>
                    <a href="#" ng-click="closeModal()" style="color: black" class="icon-close-modal right"><i class="mdi mdi-close"></i></a>
                </h1>
                <div class="row">
                    <div class="col s12">
                        <div class="col s6">
                            <label class="active" for="numeroDocumento">Nº do Documento</label>
                            <input class="validate" type="text" ng-model="model.numeroDocumento" name="numeroDocumento" id="numeroDocumento" data-label="Número do Documento" placeholder="Digite o número do documento" ng-required="true" ng-class="{'invalid-form': formPedido.numeroDocumento.$error.required}"/>
                        </div>
                        <div class="col s6">
                            <label class="active" for="dataEmissao">Data de Emissão</label>
                            <input class="validate" type="date" ng-model="model.dataEmissao" ng-model-options="{timezone: 'UTC'}" name="dataEmissao" id="dataEmissao" data-label="Data de Emissão" ng-required="true" ng-class="{'invalid-form': formPedido.dataEmissao.$error.required}"/>
                        </div>
                        <div class="col s6">
                            <label class="active" for="cliente">Clientes</label>
                            <select class="browser-default" ng-model="model.idCliente" ng-options="cliente.id as cliente.nome for cliente in clientes" ng-init="resetSelect()" name="idCliente" id="idCliente" data-label="Cliente" ng-required="true" ng-class="{'invalid-form': formPedido.idCliente.$error.required}">
                                <option value="">Selecione um cliente</option>
                            </select>
                        </div>
                        <div class="col s12" ng-show="animais == ''"><br/>
                            <p class="center">Você não tem nenhum animal cadastrado no momento. Porém você pode criar o pedido e depois inserir animais nele!</p>
                        </div>

                        <div class="col s12" ng-show="model.situacao != 3 && model.situacao != 4 && animais != ''">
                            <label class="active" for="animais">Animais</label>
                            <p>Selecione os animais que deseja adicionar ao pedido e em seguida o valor de cada um.</p>
                            <div ng-repeat="animal in animais track by $index">
                                <div class="col s12 m6 l3">
                                    <div class="col s4 m4 l4">
                                        <input ng-model="list[animal.id].status" ng-true-value="1" ng-false-value="0" type="checkbox" id="{{animal.id}}" />
                                        <label for="{{animal.id}}">{{animal.id}}</label>
                                    </div>
                                    <div class="col s8 m8 l8">
                                        <input type="text" ui-money-mask class="input-valor-animal" ng-model="list[animal.id].valorUnitario" ng-if="list[animal.id].status"  placeholder="Valor Unitário"  name="valorUnitario" id="valorUnitario"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12" ng-show="model.valorTotal">
                            <p class="right"><b>Valor Total:</b> {{model.valorTotal| currency: "R$ "}}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a class="btn modal-action waves-effect waves-green" ng-show="model.situacao != 3 && model.situacao != 4" ng-click="addPedido()"><i class="mdi mdi-{{btnIcon}}"></i>{{btnSalvar}}</a>
                <a class="btn modal-action modal-close waves-effect waves-green blue" ng-show="model.situacao == 1" ng-click="updateStatusPedido(2)"><i class="mdi mdi-cash-multiple"></i> Finalizar</a>
                <a class="btn modal-action modal-close waves-effect waves-green red" ng-show="model.situacao == 1" ng-click="estornarCancelarPedido(3)"><i class="mdi mdi-close"></i> Cancelar</a>
                <a class="btn modal-action modal-close waves-effect waves-green red" ng-show="model.situacao == 2" ng-click="estornarCancelarPedido(4)"><i class="mdi mdi-block-helper"></i> Estornar</a>
                <p ng-show="model.situacao == 3" class="center red-text">Este pedido foi Cancelado!</p>
                <p ng-show="model.situacao == 4" class="center orange-text">Este pedido foi Estornado!</p>
            </div>
        </form>
    </div>

    <table class="striped centered responsive-table">
        <thead>
            <tr>
                <th>Código</th>
                <th>Número Documento</th>
                <th>Cliente</th>
                <th>Data de Criação</th>
                <th>Valor Total</th>
                <th>Situação</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="pedido in pedidos">
                <td>{{pedido.id}}</td>
                <td>{{pedido.numeroDocumento}}</td>
                <td>{{pedido.cliente}}</td>
                <td>{{pedido.dataCriacao| tccDate : "dd/MM/yyyy"}}</td>
                <td>{{pedido.valorTotal| currency: "R$ " }}</td>
                <td>{{getSituation(pedido.situacao)}}</td>
                <td><a href="#" ng-click="openModal(pedido)">Ver/Editar</a></td>
            </tr>
        </tbody>
    </table>
</main>