<main ng-controller="racaoController">
    <!-- Modal Trigger -->
    <a class="right waves-effect waves-light btn" ng-click="modal()"><i class="mdi mdi-plus"></i>Novo</a>
    <a class="right waves-effect waves-light btn purple" href="/racao/exportar" target="_blank"><i class="mdi mdi-download"></i>Exportar</a>

    <!-- MODAL NOVA RAÇÃO -->
    <div id="newRacao" class="modal">
        <div class="modal-content">
            <h1 class="title-modal centered">{{titleModal}}</h1>
            <a href="#" ng-click="closeModal()" style="color: black" class="right icon-close-modal"><i class="mdi mdi-close"></i></a>
            <div class="row">
                <div class="col s12">
                    <form name="formRacao" method="POST" action="#">
                        <div class="col s12 m6">
                            <label class="active" for="nome">Nome</label>
                            <input class="validate" type="text" ng-model="model.nome" name="nome" id="nome" data-label="Nome" placeholder="Digite o nome" ng-required="true" ng-class="{'invalid-form': formRacao.nome.$error.required}"/>
                        </div>
                        <div class="col s12">
                            <label class="active" for="descricao">Descrição</label>
                            <textarea id="descricao" class="validate" type="textarea" name="descricao" ng-model="model.descricao"></textarea>
                        </div>
                        <div class="modal-footer">
                            <a class="btn modal-action waves-effect waves-green" ng-click="salvarRacao()"><i class="mdi mdi-{{btnIcon}}"></i>{{btnSalvar}}</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <table class="striped centered responsive-table">
        <thead>
            <tr>
                <th>Código</th>
                <th>Nome</th>
                <th>Data de Cadastro</th>
                <!--<th>Preço</th>-->
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="racao in racoes| orderBy: '-id'">
                <td>{{racao.id}}</td>
                <td>{{racao.nome}}</td>
                <td>{{racao.dataCadastro| tccDate}}</td>
                <!--<td>{{racao.preco| currency : 'R$ '}}</td>-->
                <td>
                    <a style="cursor: pointer" ng-click="modal(racao)">Editar</a> |
                    <a style="cursor: pointer" ng-click="excluir(racao.id)">Excluir</a>
                </td>
            </tr>
        </tbody>
    </table>
</main>