<main ng-controller="racaoController">
    <!-- Modal Trigger -->
    <a class="right waves-effect waves-light btn" ng-click="modal()"><i class="mdi mdi-plus"></i>Novo</a>
    <!-- Modal Structure -->
    <div id="newRacao" class="modal">
        <div class="modal-content">
            <h1 class="title-modal centered">Cadastrar Ração</h1>
            <a href="#" style="color: black" class="icon-close-modal right"><i class="mdi mdi-close"></i></a>
            <div class="row">
                <div class="col s12">
                    <form method="POST" action="#">
                        <div class="col s12 m6">
                            <label class="active" for="nome">Nome</label>
                            <input class="validate" id="nome" type="text" name="nome" ng-model="model.nome" required/>
                        </div>
                        <div class="col s12 m6">
                            <label class="active" for="unidadeMedida">Unidade medida</label>
                            <select class="browser-default" ng-model="model.unidadeMedida" ng-init="resetSelect()">
                                <option>Quilogramas</option>
                                <option>Sacaria</option>
                            </select>
                        </div>
<!--                        <div class="col s12 m6">
                            <label class="active" for="custo">Preço</label>
                            <input class="validate" type="number" name="preco" ng-model="model.preco" required/>
                        </div>-->
                        <div class="col s12 m6">
                            <label class="active" for="statusVenda">Quantidade</label>
                            <input class="validate" type="number" name="quantidade" ng-model="model.quantidade" placeholder="Digite a quantidade" required/>
                        </div>
                        <div class="col s12 m6">
                            <label class="active" for="descricao">Descrição</label>
                            <input class="validate" type="text" name="descricao" ng-model="model.descricao" required/>
                        </div>
                        <div class="modal-footer">
                            <a class="btn modal-action modal-close waves-effect waves-green" ng-click="salvarRacao()">Salvar Ração</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <table class="striped centered responsive-table">
        <thead>
            <tr>
                <th>Código</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Data de Cadastro</th>
                <!--<th>Preço</th>-->
                <th>Quantidade</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="racao in racoes| orderBy: '-id'">
                <td>{{racao.id}}</td>
                <td>{{racao.nome}}</td>
                <td>{{racao.descricao}}</td>
                <td>{{racao.dataCadastro| tccDate}}</td>
                <!--<td>{{racao.preco| currency : 'R$ '}}</td>-->
                <td>{{racao.quantidade}}</td>
                <td>
                    <!--<a style="cursor: pointer" ng-click="openDetailsModal(animal.id)">Ver</a> |--> 
                    <a style="cursor: pointer" ng-click="modal(animal)">Editar</a> | 
                    <a style="cursor: pointer" ng-click="excluir(animal.id)">Excluir</a>
                </td>
            </tr>
        </tbody>
    </table>
</main>