<main ng-controller="vacinaController">
    <!-- Modal Trigger -->
    <a class="right waves-effect waves-light btn" ng-click="modal()"><i class="mdi mdi-plus"></i>Novo</a>
    <a class="right waves-effect waves-light btn purple" href="/vacina/exportar" target="_blank" ng-if="animais != ''"><i class="mdi mdi-download"></i>Exportar</a>

    <!-- MODAL NOVA VACINA-->
    <div id="newVaccine" class="modal">
        <div class="modal-content">
            <h1 class="title-modal centered">Inserir Vacina - Medicamento</h1>
            <a href="#" ng-click="closeModal()" style="color: black" class="right icon-close-modal"><i class="mdi mdi-close"></i></a>
            <div class="row">
                <div class="col s12">
                    <form name="formVacina" method="POST" action="#">
                        <br/>
                        <div class="col s12 m6">
                            <label class="active" for="nome">Nome</label>
                            <input class="validate" type="text" ng-model="model.nome"  name="nome" id="nome" data-label="Nome" placeholder="Digite o nome" ng-required="true" ng-class="{'invalid-form': formVacina.nome.$error.required}"/>
                        </div>
                        <div class="col s12 m6">
                            <label class="active" for="dosagem">Dosagem por Quilo (ml)</label>
                            <input class="validate" ui-number-mask type="text" name="dosagem" ng-model="model.dosagem"/>
                        </div>
                        <div class="col s12">
                            <label class="active" for="descricao">Descrição</label>
                            <textarea id="descricao" class="validate" type="textarea" name="descricao" ng-model="model.descricao"></textarea>
                        </div>                        
                        <div class="modal-footer">
                            <a class="btn modal-action waves-effect waves-green"  ng-show="!chekboxInsert" ng-click="addVaccine()">Salvar Vacina</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <table class="striped centered responsive-table">
        <thead>
            <tr>
                <th>Código</th>
                <th>Nome</th>
                <!--<th>Custo</th>-->
                <th>Data de Cadastro</th>
                <th>Dosagem (ml)</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="vacina in vacinas">
                <td>{{vacina.id}}</td>
                <td>{{vacina.nome}}</td>
                <!--<td>{{vacina.custo| currency : 'R$ '}}</td>-->
                <td>{{vacina.dataCadastro| tccDate}}</td>
                <td>{{vacina.dosagem| tccMl}}</td>
                <td><a style="cursor: pointer" ng-click="modal(vacina)">Editar</a> | <a style="cursor: pointer" ng-click="delete(vacina.id)">Excluir</a></td>
            </tr>
        </tbody>
    </table>
</main>
<!-- Usa-se a variável $animal pq no model uso o método extract() que transforma todos os indices de um array em uma variável -->