<main ng-controller="vacinaController">
    <!-- Modal Trigger -->
    <a class="right waves-effect waves-light btn" ng-click="modal()"><i class="mdi mdi-plus"></i>Novo</a>
    <!-- Modal Structure -->
    <div id="newVacina" class="modal">
        <div class="modal-content">
            <h1 class="title-modal centered">Vacinar Animal</h1>
            <a href="#" style="color: black" class="closeModal right"><i class="mdi mdi-close"></i></a>
            <div class="row">
                <div class="col s12">
                    <form method="POST" action="#">
                        <div class="row" ng-show="!model.id">
                            <div class="col s6">
                                <p>
                                    <input ng-model="chekboxInsert" type="checkbox" id="teste" />
                                    <label for="teste">Vacinar Vários?</label>
                                </p>
                            </div>
                        </div>
                        <div ng-show="!chekboxInsert">
                            <div class="col s6">
                                <label class="active" for="apelido">Nome</label>
                                <input class="validate" id="nome" type="text" name="nome" ng-model="model.nome" required/>
                            </div>
                            <div class="col s6">
                                <label class="active" for="custo">Custo</label>
                                <input class="validate" type="number" name="custo" ng-model="model.custo" required/>
                            </div>
                        </div>
                        <div ng-show="chekboxInsert">
                            <div class="col s6">
                                <label class="active" for="statusVenda">Quantidade</label>
                                <input class="validate" type="number" name="quantidade" ng-model="model.quantidade" placeholder="Digite a quantidade" required/>
                            </div>
                            <div class="col s6">
                                <label class="active" for="custoTotal">Custo Total</label>
                                <input class="validate" type="number" name="custoTotal" ng-model="model.custoTotal" placeholder="Será divido pela quantidade" required/>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a class="btn modal-action modal-close waves-effect waves-green"  ng-show="!chekboxInsert" ng-click="addAnimal()">Salvar Animal</a>
                            <a class="btn modal-action modal-close waves-effect waves-green" ng-show="chekboxInsert" ng-click="insertMultiple()">Inserir Vários</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <div id="aplicar-vacina-modal" class="modal">
        <div class="modal-content">
            <h1 class="title-modal centered">Aplicar Vacina</h1>
            <a href="#" style="color: black" class="closeModal right"><i class="mdi mdi-close"></i></a>
            <div class="row">
                <div class="col s12">
                    <form method="POST" action="#">
                        <div class="col s6">
                            <label class="active" for="codigo">Nº do Documento</label>
                            <input class="validate" id="apelido" type="text" name="codigo" ng-model="sell.numeroDocumento" required/>
                        </div>
                        <div class="col s6">
                            <label class="active" for="dataCriacao">Data de Criação</label>
                            <input class="validate" type="date" name="dataCriacao" ng-model="sell.dataCriacao" required/>
                        </div>
                        <div class="modal-footer">
                            <a class="btn modal-action modal-close waves-effect waves-green" ng-click="sellAnimals()"><i class="mdi mdi-check"></i>Adicionar Pedido</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!--    <div>
            <h4 ng-bind="app"></h4>
            <a href="#" ng-click="open()">Teste</a>
        </div>-->

    <table class="striped centered responsive-table">
        <thead>
            <tr>
                <th>Código</th>
                <th>Nome</th>
                <th>Custo</th>
                <!--<th>Data de Cadastro</th>-->
                <!--<th>Custo</th>-->
                <!--<th><a class="waves-effect waves-light btn" ng-click="openAplicarVacinaModal()">Aplicar?</a></th>-->
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="vacina in vacinas">
                <td>{{vacina.id}}</td>
                <td>{{vacina.nome}}</td>
                <td>{{vacina.custo| currency : 'R$ '}}</td>
                <!--<td>{{animal.dataCadastro| tccDate}}</td>-->
                <!--<td>{{animal.custo| currency : 'R$ '}}</td>-->
<!--                <td>
                    <input ng-model="sell[animal.id]" ng-true-value="1" ng-false-value="0" type="checkbox" id="{{animal.id}}" />
                    <label for="{{animal.id}}"></label>
                </td>-->
                <td><a style="cursor: pointer" ng-click="modal(vacina)">Editar</a> | <a style="cursor: pointer" ng-click="excluir(vacina.id)">Excluir</a></td>
            </tr>
        </tbody>
    </table>
</main>
<!-- Usa-se a variável $animal pq no model uso o método extract() que transforma todos os indices de um array em uma variável -->