        <script type="text/javascript" src="<?= ASSETS ?>js/jquery-2.1.4.min.js"></script>
        <script type="text/javascript" src="<?= ASSETS ?>js/materialize.js"></script>
        <script type="text/javascript" src="<?= ASSETS ?>js/angular.js"></script>
        <script type="text/javascript" src="<?= ANGULAR ?>modules/tccModule.js"></script>
        <script type="text/javascript" src="<?= ANGULAR ?>controllers/animalController.js"></script>
        <script type="text/javascript" src="<?= ANGULAR ?>controllers/clienteController.js"></script>
        <script type="text/javascript" src="<?= ANGULAR ?>controllers/pedidoController.js"></script>
        <script type="text/javascript" src="<?= ANGULAR ?>services/animalService.js"></script>
        <script type="text/javascript" src="<?= ANGULAR ?>services/pedidoService.js"></script>
        <script type="text/javascript" src="<?= ANGULAR ?>services/clienteService.js"></script>
        <script type="text/javascript" src="<?= ANGULAR ?>filter/date.js"></script>
        <script type="text/javascript" src="<?= ASSETS ?>js/app.js"></script>
    </body>
</html>