<?php
error_reporting(-1);
?>
<!DOCTYPE html>
<html lang="pt-br" ng-app="tcc">
    <head>
        <!--<link type="text/css" rel="stylesheet" href="<?= ASSETS ?>css/font-awesome.min.css" media="screen,projection"/>-->
        <link href="<?= ASSETS ?>font/icons/materialdesignicons.min.css" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?= ASSETS ?>css/materialize.css" media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="<?= ASSETS ?>css/style.css"/>
        <!--<link type="text/css" rel="stylesheet" href="<?= ASSETS ?>css/dashboard.css">-->
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta charset="UTF-8">
        <title>Agro Boi</title>
    </head>
    <body>
        <nav>
            <ul class="side-nav fixed">
                <li class="logo" style="padding: 0 0 90px 0;">
                    <a href="<?= URL_MAIN ?>" class="waves-effect waves-teal" id="logo-container" class="brand-logo"><i class="mdi mdi-book-open left"></i>Pagina Inicial</a>
                </li>        
                <li class="bold no-padding"><a href="<?= URL_MAIN ?>animal" class="waves-effect waves-teal"><i class="mdi mdi-cow left"></i>Animais</a></li>
                <li class="bold no-padding"><a href="<?= URL_MAIN ?>racao" class="waves-effect waves-teal"><i class="mdi mdi-paw left"></i>Rações</a></li>
                <li class="bold no-padding"><a href="<?= URL_MAIN ?>pedido" class="waves-effect waves-teal"><i class="mdi mdi-wallet-travel left"></i>Pedidos</a></li>
                <li class="bold no-padding"><a href="<?= URL_MAIN ?>vacina" class="waves-effect waves-teal"><i class="mdi mdi-needle left"></i>Vacinas</a></li>
                <li class="bold no-padding"><a href="<?= URL_MAIN ?>vacinaAplicacao" class="waves-effect waves-teal"><i class="mdi mdi-needle left"></i>Aplicação de Vacinas</a></li>
                <li class="bold no-padding"><a href="<?= URL_MAIN ?>cliente" class="waves-effect waves-teal"><i class="mdi mdi-account-multiple left"></i>Clientes</a></li>
                <li class="bold no-padding"><a href="<?= URL_MAIN ?>contato" class="waves-effect waves-teal"><i class="mdi mdi-cellphone-android left"></i>Contato / Suporte</a></li>
                <!--<li class="bold no-padding"><a href="#" class="waves-effect waves-teal">Vendas</a></li>-->
                <!--<li class="bold no-padding"><a href="#" class="waves-effect waves-teal">Remédios</a></li>-->
            </ul>
            <ul id="slide-out" class="side-nav">
                <li><a href="#!">First Sidebar Link</a></li>
                <li><a href="#!">Second Sidebar Link</a></li>
                <li class="no-padding">
                    <ul class="collapsible collapsible-accordion">
                        <li>
                            <a class="collapsible-header">Dropdown<i class="mdi-navigation-arrow-drop-down"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li><a href="#!">First</a></li>
                                    <li><a href="#!">Second</a></li>
                                    <li><a href="#!">Third</a></li>
                                    <li><a href="#!">Fourth</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>

            <div class="center" style="font-size: 25px;">Agro Boi</div>

            <!--            <ul class="hide-on-med-and-down">
                            <li><a href="#!">Link 1</a></li>
                            <li><a href="#!">Link 2</a></li>
                            <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Menu<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
                            <ul id='dropdown1' class='dropdown-content'>
                                <li><a href="#!">Opção 1</a></li>
                                <li><a href="#!">Opção 2</a></li>
                                <li><a href="#!">Opção 3</a></li>
                                <li><a href="#!">Opção 4</a></li>
                            </ul>
                        </ul>-->
            <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
        </nav>